/**
 * Hardcoded character data extracted from Rick and Morty API
 * Total characters analyzed: 826
 * Last updated: 2025-10-10
 */

export interface FilterOption {
  value: string;
  label: string;
}

// 10 unique species found in the API
export const CHARACTER_SPECIES_OPTIONS: FilterOption[] = [
  { value: '', label: 'All Species' },
  { value: 'alien', label: 'Alien' },
  { value: 'animal', label: 'Animal' },
  { value: 'cronenberg', label: 'Cronenberg' },
  { value: 'disease', label: 'Disease' },
  { value: 'human', label: 'Human' },
  { value: 'humanoid', label: 'Humanoid' },
  { value: 'mythological creature', label: 'Mythological Creature' },
  { value: 'poopybutthole', label: 'Poopybutthole' },
  { value: 'robot', label: 'Robot' },
  { value: 'unknown', label: 'unknown' }
];

// 169 unique types found in the API
export const CHARACTER_TYPE_OPTIONS: FilterOption[] = [
  { value: '', label: 'All Types' },
  { value: 'alligator-person', label: 'Alligator-Person' },
  { value: 'alphabetrian', label: 'Alphabetrian' },
  { value: 'amoeba-person', label: 'Amoeba-Person' },
  { value: 'animal', label: 'Animal' },
  { value: 'anime', label: 'Anime' },
  { value: 'artificial intelligence', label: 'Artificial Intelligence' },
  { value: 'bepisian', label: 'Bepisian' },
  { value: 'bird-person', label: 'Bird-Person' },
  { value: 'bird-person human mix', label: 'Bird-Person Human Mix' },
  { value: 'blue ape alien', label: 'Blue ape alien' },
  { value: 'boobie buyer reptilian', label: 'Boobie buyer reptilian' },
  { value: 'boobloosian', label: 'Boobloosian' },
  { value: 'bread', label: 'Bread' },
  { value: 'chud', label: 'CHUD' },
  { value: 'chud human mix', label: 'CHUD Human Mix' },
  { value: 'cat', label: 'Cat' },
  { value: 'cat controlled dead lady', label: 'Cat controlled dead lady' },
  { value: 'cat-person', label: 'Cat-Person' },
  { value: 'caterpillar', label: 'Caterpillar' },
  { value: 'centaur', label: 'Centaur' },
  { value: 'chair', label: 'Chair' },
  { value: 'changeformer', label: 'Changeformer' },
  { value: 'clay-person', label: 'Clay-Person' },
  { value: 'clone', label: 'Clone' },
  { value: 'cone-nippled alien', label: 'Cone-nippled alien' },
  { value: 'conjoined twin', label: 'Conjoined twin' },
  { value: 'cookie', label: 'Cookie' },
  { value: 'corn-person', label: 'Corn-person' },
  { value: 'cromulon', label: 'Cromulon' },
  { value: 'cronenberg', label: 'Cronenberg' },
  { value: 'crow', label: 'Crow' },
  { value: 'crow horse', label: 'Crow Horse' },
  { value: 'cyborg', label: 'Cyborg' },
  { value: 'decoy', label: 'Decoy' },
  { value: 'demon', label: 'Demon' },
  { value: 'dog', label: 'Dog' },
  { value: 'doopidoo', label: 'Doopidoo' },
  { value: 'dragon', label: 'Dragon' },
  { value: 'drumbloxian', label: 'Drumbloxian' },
  { value: 'dummy', label: 'Dummy' },
  { value: 'eat shiter-person', label: 'Eat shiter-Person' },
  { value: 'eel', label: 'Eel' },
  { value: 'elephant-person', label: 'Elephant-Person' },
  { value: 'ferkusian', label: 'Ferkusian' },
  { value: 'ferret robot', label: 'Ferret Robot' },
  { value: 'fish-person', label: 'Fish-Person' },
  { value: 'flansian', label: 'Flansian' },
  { value: 'floop floopian', label: 'Floop Floopian' },
  { value: 'fly', label: 'Fly' },
  { value: 'game', label: 'Game' },
  { value: 'garblovian', label: 'Garblovian' },
  { value: 'gazorpian', label: 'Gazorpian' },
  { value: 'gazorpian reproduction robot', label: 'Gazorpian reproduction robot' },
  { value: 'gear-person', label: 'Gear-Person' },
  { value: 'genetic experiment', label: 'Genetic experiment' },
  { value: 'giant', label: 'Giant' },
  { value: 'giant cat monster', label: 'Giant Cat Monster' },
  { value: 'giant incest baby', label: 'Giant Incest Baby' },
  { value: 'glorzo', label: 'Glorzo' },
  { value: 'god', label: 'God' },
  { value: 'goddess', label: 'Goddess' },
  { value: 'gramuflackian', label: 'Gramuflackian' },
  { value: 'grandma', label: 'Grandma' },
  { value: 'greebybobe', label: 'Greebybobe' },
  { value: 'gromflomite', label: 'Gromflomite' },
  { value: 'guinea pig for the polio vaccine', label: 'Guinea Pig for the Polio Vaccine' },
  { value: 'hairy alien', label: 'Hairy alien' },
  { value: 'half soulless puppet', label: 'Half Soulless Puppet' },
  { value: 'hammerhead-person', label: 'Hammerhead-Person' },
  { value: 'hivemind', label: 'Hivemind' },
  { value: 'hole', label: 'Hole' },
  { value: 'hologram', label: 'Hologram' },
  { value: 'human gazorpian', label: 'Human Gazorpian' },
  { value: 'human with a flower in his head', label: 'Human with a flower in his head' },
  { value: 'human with antennae', label: 'Human with antennae' },
  { value: 'human with ants in his eyes', label: 'Human with ants in his eyes' },
  { value: 'human with baby legs', label: 'Human with baby legs' },
  { value: 'human with giant head', label: 'Human with giant head' },
  { value: 'human with tusks', label: 'Human with tusks' },
  { value: 'human-snake hybrid', label: 'Human-Snake hybrid' },
  { value: 'interdimensional gaseous being', label: 'Interdimensional gaseous being' },
  { value: 'jellybean', label: 'Jellybean' },
  { value: 'korblock', label: 'Korblock' },
  { value: 'krootabulan', label: 'Krootabulan' },
  { value: 'larva alien', label: 'Larva alien' },
  { value: 'leprechaun', label: 'Leprechaun' },
  { value: 'light bulb-alien', label: 'Light bulb-Alien' },
  { value: 'little human', label: 'Little Human' },
  { value: 'lizard', label: 'Lizard' },
  { value: 'lizard-person', label: 'Lizard-Person' },
  { value: 'lobster-alien', label: 'Lobster-Alien' },
  { value: 'mannie', label: 'Mannie' },
  { value: 'mascot', label: 'Mascot' },
  { value: 'meeseeks', label: 'Meeseeks' },
  { value: 'mega gargantuan', label: 'Mega Gargantuan' },
  { value: 'memory', label: 'Memory' },
  { value: 'mexican', label: 'Mexican' },
  { value: 'microverse inhabitant', label: 'Microverse inhabitant' },
  { value: 'miniverse inhabitant', label: 'Miniverse inhabitant' },
  { value: 'monogatron', label: 'Monogatron' },
  { value: 'monster', label: 'Monster' },
  { value: 'morglutzian', label: 'Morglutzian' },
  { value: "morty's toxic side", label: "Morty's toxic side" },
  { value: 'mytholog', label: 'Mytholog' },
  { value: 'nano alien', label: 'Nano Alien' },
  { value: 'narnian', label: 'Narnian' },
  { value: 'necrophiliac', label: 'Necrophiliac' },
  { value: 'normal size bug', label: 'Normal Size Bug' },
  { value: 'numbericon', label: 'Numbericon' },
  { value: 'octopus-person', label: 'Octopus-Person' },
  { value: 'old amazons', label: 'Old Amazons' },
  { value: 'omniscient being', label: 'Omniscient being' },
  { value: 'organic gun', label: 'Organic gun' },
  { value: 'parasite', label: 'Parasite' },
  { value: 'passing butter robot', label: 'Passing Butter Robot' },
  { value: 'phone', label: 'Phone' },
  { value: 'phone-person', label: 'Phone-Person' },
  { value: 'pickle', label: 'Pickle' },
  { value: 'pizza', label: 'Pizza' },
  { value: 'planet', label: 'Planet' },
  { value: 'plutonian', label: 'Plutonian' },
  { value: 'pripudlian', label: 'Pripudlian' },
  { value: 'rat', label: 'Rat' },
  { value: "rick's toxic side", label: "Rick's toxic side" },
  { value: 'ring-nippled alien', label: 'Ring-nippled alien' },
  { value: 'robot', label: 'Robot' },
  { value: 'robot-crocodile hybrid', label: 'Robot-Crocodile hybrid' },
  { value: 'scarecrow', label: 'Scarecrow' },
  { value: 'scrotian', label: 'Scrotian' },
  { value: 'self-aware arm', label: 'Self-aware arm' },
  { value: 'sentient ant colony', label: 'Sentient ant colony' },
  { value: 'sexy aquaman', label: 'Sexy Aquaman' },
  { value: 'shapeshifter', label: 'Shapeshifter' },
  { value: 'shimshamian', label: 'Shimshamian' },
  { value: 'shrimp', label: 'Shrimp' },
  { value: 'slartivartian', label: 'Slartivartian' },
  { value: 'slug', label: 'Slug' },
  { value: 'snail alien', label: 'Snail alien' },
  { value: 'snake', label: 'Snake' },
  { value: 'soulless puppet', label: 'Soulless Puppet' },
  { value: 'squid', label: 'Squid' },
  { value: 'stair goblin', label: 'Stair goblin' },
  { value: 'starfish', label: 'Starfish' },
  { value: 'summon', label: 'Summon' },
  { value: 'super sperm monster', label: 'Super Sperm Monster' },
  { value: 'superhuman', label: 'Superhuman' },
  { value: 'superhuman (ghost trains summoner)', label: 'Superhuman (Ghost trains summoner)' },
  { value: 'teddy bear', label: 'Teddy Bear' },
  { value: 'teenyverse inhabitant', label: 'Teenyverse inhabitant' },
  { value: 'tentacle alien', label: 'Tentacle alien' },
  { value: 'the devil', label: 'The Devil' },
  { value: 'tiger', label: 'Tiger' },
  { value: 'time god', label: 'Time God' },
  { value: 'tinymouth', label: 'Tinymouth' },
  { value: 'toy', label: 'Toy' },
  { value: 'traflorkian', label: 'Traflorkian' },
  { value: 'trunk-person', label: 'Trunk-Person' },
  { value: 'tumblorkian', label: 'Tumblorkian' },
  { value: 'turkey', label: 'Turkey' },
  { value: 'turkey human mix', label: 'Turkey Human Mix' },
  { value: 'tuskfish', label: 'Tuskfish' },
  { value: 'unknown-nippled alien', label: 'Unknown-nippled alien' },
  { value: 'vampire', label: 'Vampire' },
  { value: 'wasp', label: 'Wasp' },
  { value: 'weasel', label: 'Weasel' },
  { value: 'whenwolf', label: 'Whenwolf' },
  { value: 'zeus', label: 'Zeus' },
  { value: 'zigerion', label: 'Zigerion' },
  { value: 'zombodian', label: 'Zombodian' }
];

// Species list for quick reference
export const SPECIES_LIST = [
  "Alien",
  "Animal",
  "Cronenberg",
  "Disease",
  "Human",
  "Humanoid",
  "Mythological Creature",
  "Poopybutthole",
  "Robot",
  "unknown"
];

// Types list for quick reference  
export const TYPES_LIST = [
  "Alligator-Person",
  "Alphabetrian",
  "Amoeba-Person",
  "Animal",
  "Anime",
  "Artificial Intelligence",
  "Bepisian",
  "Bird-Person",
  "Bird-Person Human Mix",
  "Blue ape alien",
  "Boobie buyer reptilian",
  "Boobloosian",
  "Bread",
  "CHUD",
  "CHUD Human Mix",
  "Cat",
  "Cat controlled dead lady",
  "Cat-Person",
  "Caterpillar",
  "Centaur",
  "Chair",
  "Changeformer",
  "Clay-Person",
  "Clone",
  "Cone-nippled alien",
  "Conjoined twin",
  "Cookie",
  "Corn-person",
  "Cromulon",
  "Cronenberg",
  "Crow",
  "Crow Horse",
  "Cyborg",
  "Decoy",
  "Demon",
  "Dog",
  "Doopidoo",
  "Dragon",
  "Drumbloxian",
  "Dummy",
  "Eat shiter-Person",
  "Eel",
  "Elephant-Person",
  "Ferkusian",
  "Ferret Robot",
  "Fish-Person",
  "Flansian",
  "Floop Floopian",
  "Fly",
  "Game",
  "Garblovian",
  "Gazorpian",
  "Gazorpian reproduction robot",
  "Gear-Person",
  "Genetic experiment",
  "Giant",
  "Giant Cat Monster",
  "Giant Incest Baby",
  "Glorzo",
  "God",
  "Goddess",
  "Gramuflackian",
  "Grandma",
  "Greebybobe",
  "Gromflomite",
  "Guinea Pig for the Polio Vaccine",
  "Hairy alien",
  "Half Soulless Puppet",
  "Hammerhead-Person",
  "Hivemind",
  "Hole",
  "Hologram",
  "Human Gazorpian",
  "Human with a flower in his head",
  "Human with antennae",
  "Human with ants in his eyes",
  "Human with baby legs",
  "Human with giant head",
  "Human with tusks",
  "Human-Snake hybrid",
  "Interdimensional gaseous being",
  "Jellybean",
  "Korblock",
  "Krootabulan",
  "Larva alien",
  "Leprechaun",
  "Light bulb-Alien",
  "Little Human",
  "Lizard",
  "Lizard-Person",
  "Lobster-Alien",
  "Mannie",
  "Mascot",
  "Meeseeks",
  "Mega Gargantuan",
  "Memory",
  "Mexican",
  "Microverse inhabitant",
  "Miniverse inhabitant",
  "Monogatron",
  "Monster",
  "Morglutzian",
  "Morty's toxic side",
  "Mytholog",
  "Nano Alien",
  "Narnian",
  "Necrophiliac",
  "Normal Size Bug",
  "Numbericon",
  "Octopus-Person",
  "Old Amazons",
  "Omniscient being",
  "Organic gun",
  "Parasite",
  "Passing Butter Robot",
  "Phone",
  "Phone-Person",
  "Pickle",
  "Pizza",
  "Planet",
  "Plutonian",
  "Pripudlian",
  "Rat",
  "Rick's toxic side",
  "Ring-nippled alien",
  "Robot",
  "Robot-Crocodile hybrid",
  "Scarecrow",
  "Scrotian",
  "Self-aware arm",
  "Sentient ant colony",
  "Sexy Aquaman",
  "Shapeshifter",
  "Shimshamian",
  "Shrimp",
  "Slartivartian",
  "Slug",
  "Snail alien",
  "Snake",
  "Soulless Puppet",
  "Squid",
  "Stair goblin",
  "Starfish",
  "Summon",
  "Super Sperm Monster",
  "Superhuman",
  "Superhuman (Ghost trains summoner)",
  "Teddy Bear",
  "Teenyverse inhabitant",
  "Tentacle alien",
  "The Devil",
  "Tiger",
  "Time God",
  "Tinymouth",
  "Toy",
  "Traflorkian",
  "Trunk-Person",
  "Tumblorkian",
  "Turkey",
  "Turkey Human Mix",
  "Tuskfish",
  "Unknown-nippled alien",
  "Vampire",
  "Wasp",
  "Weasel",
  "Whenwolf",
  "Zeus",
  "Zigerion",
  "Zombodian"
];

